### PR TITLE
Fix some html details and update some styles

### PR DESCRIPTION
**Pull request by mrluisfer**
Just fixed some basic bugs in your html as well as styles not displaying correctly

I also improved a bit its metatags also it had a Vite configuration using the html plugin but apparently they just deleted it, but it's ok
I also added a suggestion in your gitignore

### CODE REVIEW

**Comment by mrluisfer** [comment]
This last commit was because the countEffect is not being used and when executing tsc for production it gives an error
netlify logs

**Comment by EmmaG2** [comment]
# Info
No puedo hacer un merge a la PR, porque el css se rompe

**Comment by mrluisfer** [comment]
That was because there was the html plugin setting that vite uses, so the parser tries to parse the tags even if they aren't properly closed

error img

**Comment by EmmaG2** [comment]
done

**Pull request merged**
